name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v3
      - name: Get swift version
        run: swift --version # Swift 6.2

      - name: Run tests
        run: swift test
